# netlify.toml
[build]
  command = "npm run build"
  # For Next.js + @netlify/plugin-nextjs, publish can be ".next" (plugin will handle server artifacts)
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
